import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>WebFactory.Ninja - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Link href="/">
            <Image
              className={styles.logo}
              src="/logo.svg"
              alt="WebFactory Logo"
              width={350}
              height={350}
              priority
            />
          </Link>
        </div>

        <div className={styles.contact}>
          <h2 className={inter.className}>Contact Us</h2>
          <p className={inter.className}>
            Get in touch instantly with us via
            <a href="mailto:hi@webfactory.ninja">hi@webfactory.ninja</a>
            or contact our CEO directly via
            <a href="mailto:denis@webfactory.ninja">denis@webfactory.ninja</a>
          </p>
        </div>

        <div className={styles.grid}>
          <Link href="/about-us" className={styles.card}>
            <h2 className={inter.className}>
              About Us <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Find information about us.</p>
          </Link>

          <Link href="/services" className={styles.card}>
            <h2 className={inter.className}>
              Services <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Find what we do.</p>
          </Link>

          <Link href="/" className={styles.card}>
            <h2 className={inter.className}>
              References <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Discover who we are.</p>
          </Link>

          <Link href="/contact-us" className={styles.card}>
            <h2 className={inter.className}>
              Contact Us <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Get in touch instantly.</p>
          </Link>
        </div>
      </main>
    </>
  );
}
